version: '3'

services:
  
  keystone:
    environment:
      - NODE_ENV=production 

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - keystone  