version: '3'

services:
  
  mongo:
    image: mongo
    volumes:
      - ./mongo/data:/data/db
      - ./dump:/dump
  
  keystone:
    build: 
      context: .
      dockerfile: node.dockerfile
    image: toc-web
    depends_on:
      - mongo
    volumes:
      - ./keystone.js:/usr/src/app/keystone.js
      - ./models:/usr/src/app/models
      - ./routes:/usr/src/app/routes
      - ./templates:/usr/src/app/templates
      - ./updates:/usr/src/app/updates
      - ./public:/usr/src/app/public