version: '3'

services:
  
  keystone:
    environment:
      - NODE_ENV=production 

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - keystone  